# modules/ifc_export.py
import ifcopenshell
import ifcopenshell.api
import uuid
from datetime import datetime

def create_ifc_file(concept, filename="arc_model.ifc"):
    """
    Generate a simple IFC file from a concept dictionary.
    """
    # Create a new IFC file (IFC4)
    file = ifcopenshell.api.run("project.create", ifc_version="IFC4")
    
    # Set project details
    project = file.by_type("IfcProject")[0]
    ifcopenshell.api.run("project.edit", project, 
                         name=f"Arc Project - {concept['type']}",
                         long_name=f"Generated by Arc AEC Engine on {datetime.now().strftime('%Y-%m-%d')}")
    
    # Create site (simplified)
    site = ifcopenshell.api.run("root.create_entity", file, 
                                 ifc_class="IfcSite",
                                 name="Site")
    
    # Create building
    building = ifcopenshell.api.run("root.create_entity", file,
                                     ifc_class="IfcBuilding",
                                     name=concept["type"])
    # Set building elevation (ground floor at 0)
    ifcopenshell.api.run("building.storey.add", file, building=building)
    
    # Create storeys (one per floor)
    floors = concept["floors"]
    storey_height = concept["structural"]["storey_height"]
    storeys = []
    for i in range(floors):
        elevation = i * storey_height
        storey = ifcopenshell.api.run("root.create_entity", file,
                                      ifc_class="IfcBuildingStorey",
                                      name=f"Level {i+1}")
        ifcopenshell.api.run("building.storey.assign", file, 
                             building_storey=storey, building=building)
        ifcopenshell.api.run("geometry.edit_object_placement", file,
                             product=storey, 
                             relative_to=site,
                             elevation=elevation)
        storeys.append(storey)
    
    # For simplicity, we'll create a rectangular footprint based on GFA
    # Total GFA / floors = floor area per storey
    total_gfa = concept["total_gfa"]
    floor_area = total_gfa / floors
    # Assume square footprint: width = depth = sqrt(floor_area)
    footprint_size = (floor_area ** 0.5)
    # Round to nearest meter for simplicity
    width = round(footprint_size)
    depth = width  # square
    
    # Create walls, slabs, columns for each storey
    for i, storey in enumerate(storeys):
        elevation = i * storey_height
        # Slab (floor)
        slab = ifcopenshell.api.run("root.create_entity", file,
                                    ifc_class="IfcSlab",
                                    name=f"Slab Level {i+1}")
        ifcopenshell.api.run("spatial.assign_container", file, 
                             product=slab, container=storey)
        # Set slab geometry – a simple box
        # We'll create a 2D representation (extruded)
        # For a full implementation, we'd use ifcopenshell.geom to create a solid,
        # but for a minimal example, we'll add a placeholder.
        # For now, just add a basic wall.
        # We'll add 4 walls per storey (perimeter)
        wall_thickness = 0.2  # meters
        wall_height = storey_height
        positions = [
            (0, 0, width, 0),     # bottom wall
            (0, depth, width, depth),  # top wall
            (0, 0, 0, depth),     # left wall
            (width, 0, width, depth)   # right wall
        ]
        for j, (x1, y1, x2, y2) in enumerate(positions):
            wall = ifcopenshell.api.run("root.create_entity", file,
                                        ifc_class="IfcWall",
                                        name=f"Wall {j+1} Level {i+1}")
            ifcopenshell.api.run("spatial.assign_container", file, 
                                 product=wall, container=storey)
            # We'll add a simple extrusion representation later
            # For now, we just create the entity.
    
    # Add a simple representation (placeholders)
    # In a real implementation, you'd use ifcopenshell.api.run("geometry.add_wall_representation")
    # to define geometry. For brevity, we'll just save the file with minimal content.
    
    # Write file
    file.write(filename)
    return filename

def generate_ifc_download(concept):
    """
    Generate an IFC file and return its contents for download.
    """
    import io
    # Create a temporary file
    filename = "arc_model.ifc"
    create_ifc_file(concept, filename)
    with open(filename, "rb") as f:
        data = f.read()
    return data